INSERT INTO bears (id, name, age, gender, color, temperament, alive) VALUES (1, "Mr. Chocolate", 8, "brown", "M", "calm", 1)
INSERT INTO bears (id, name, age, gender, color, tempermenmt, alive) VALUES (2, "Rowdy", 7, "brown", "M", "aggressive", 1)
INSERT INTO bears (id, name, age, gender, color, temperament, alive) VALUES (3, "Tabitha", 6, "white", "F", "calm", 1)
INSERT INTO bears (id, name, age, gender, color, temperament, alive) VALUES (4, "Sergent Brown", 5, "black", "M", "strict", 1)
INSERT INTO bears (id, name, age, gender, color, temperament, alive) VALUES (5, "Melissa", 4, "black", "F", "happy", 1)
INSERT INTO bears (id, name, age, gender, color, temperament, alive) VALUES (6, "Grinch", 3, "green", "M", "grumpy", 1)
INSERT INTO bears (id, name, age, gender, color, temperament, alive) VALUES (7, "Wendy", 2, "white", "F", "happy", 1)
INSERT INTO bears (id, name, age, gender, color, temperament, alive) VALUES (8, NULL, NULL, NULL, NULL, NULL, NULL)
